# Generated by Django 3.0.6 on 2020-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0004_subcategory_catid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='catname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcat',
            field=models.CharField(default='', max_length=20),
        ),
    ]
