# Generated by Django 3.0.6 on 2020-06-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20200622_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
