# Generated by Django 3.0.6 on 2020-06-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorywise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='brief',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='about',
            field=models.CharField(max_length=100),
        ),
    ]
