# Generated by Django 3.0.6 on 2020-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200604_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='main',
            name='insta',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='main',
            name='twitter',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.CharField(max_length=50000),
        ),
    ]
