# Generated by Django 3.0.6 on 2020-06-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
    ]
