# Generated by Django 3.0.6 on 2020-06-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200623_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
