# Generated by Django 3.0.6 on 2020-06-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
